### ISSUE TITLE
Your repo is so awesome

### ISSUE THREAD

**Issue by hungntv** [TimOliver/TODocumentPickerViewController#4]
Please continue to improve your repo.
BTW, what does "actionItem" do? :))
```
UIBarButtonItem *actionItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAction target:nil action:nil];
        actionItem.enabled = NO;

        self.editingToolbarItems = @[actionItem, spaceItemLeft, labelItem, spaceItemRight, self.chooseButton];
```

**Comment by TimOliver** [comment]
Haha thanks so much @hungntv! I'll try! I need to paint some more icons for it soon.

My idea for `actionItem` is so you can insert your own button and attach your own custom logic to it. I put it there because for the app I'm building this for, I want to be able to perform custom actions on any files the user taps. :)

In the demo app, it's just there as an example, so it doesn't do anything when it is tapped. :)
